
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-16
owner: ucsb-cs156-s25
repo_name: team02-s25-16
pull_requests: [{"author":{"id":"MDQ6VXNlcjQ1ODkwOTMy","is_bot":false,"login":"jeffreylin26","name":"Jeffrey Lin"},"headRefName":"jl-helprequests-b2b-tests","number":99,"title":"Jl helprequests b2b tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-16/pull/99"},{"author":{"id":"MDQ6VXNlcjQ1ODkwOTMy","is_bot":false,"login":"jeffreylin26","name":"Jeffrey Lin"},"headRefName":"jl-helprequest-integration-tests","number":98,"title":"Jl helprequest integration tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-16/pull/98"},{"author":{"id":"MDQ6VXNlcjQ1ODkwOTMy","is_bot":false,"login":"jeffreylin26","name":"Jeffrey Lin"},"headRefName":"jl-edit-helprequest-page","number":95,"title":"Jl edit helprequest page","url":"https://github.com/ucsb-cs156-s25/team02-s25-16/pull/95"},{"author":{"id":"MDQ6VXNlcjQ1ODkwOTMy","is_bot":false,"login":"jeffreylin26","name":"Jeffrey Lin"},"headRefName":"jl-index-helprequest-page","number":94,"title":"Jl index helprequest page","url":"https://github.com/ucsb-cs156-s25/team02-s25-16/pull/94"},{"author":{"id":"MDQ6VXNlcjQ1ODkwOTMy","is_bot":false,"login":"jeffreylin26","name":"Jeffrey Lin"},"headRefName":"jl-create-helprequest-page","number":93,"title":"added helprequests create page","url":"https://github.com/ucsb-cs156-s25/team02-s25-16/pull/93"},{"author":{"id":"U_kgDOCEZbAQ","is_bot":false,"login":"johnhagedorncs","name":"John Hagedorn"},"headRefName":"pc-ucsborganiation-form","number":71,"title":"Pc add form for ucsborganiation","url":"https://github.com/ucsb-cs156-s25/team02-s25-16/pull/71"}]
