
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-16
owner: ucsb-cs156-s25
repo_name: team02-s25-16
pull_requests: [{"author":{"id":"U_kgDOCEZbAQ","is_bot":false,"login":"johnhagedorncs","name":"John Hagedorn"},"headRefName":"pc-ucsborganization-fixtures","number":65,"title":"Pc - add fixtures for ucsborganization fixtures","url":"https://github.com/ucsb-cs156-s25/team02-s25-16/pull/65"},{"author":{"id":"U_kgDOBojkhQ","is_bot":false,"login":"DerekKirschbaum","name":""},"headRefName":"dk-menuitem-fixtures","number":63,"title":"Dk menuitem fixtures","url":"https://github.com/ucsb-cs156-s25/team02-s25-16/pull/63"},{"author":{"id":"U_kgDOBojkhQ","is_bot":false,"login":"DerekKirschbaum","name":""},"headRefName":"dk-menuitem-backend","number":62,"title":"dk - added backend for menu items","url":"https://github.com/ucsb-cs156-s25/team02-s25-16/pull/62"}]
