
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-16
owner: ucsb-cs156-s25
repo_name: team02-s25-16
pull_requests: [{"author":{"id":"MDQ6VXNlcjYyNDA0OTIx","is_bot":false,"login":"applechristian","name":"Christian Lee"},"headRefName":"cl-second-review-integration-test","number":145,"title":"cl - integration tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-16/pull/145"},{"author":{"id":"MDQ6VXNlcjYyNDA0OTIx","is_bot":false,"login":"applechristian","name":"Christian Lee"},"headRefName":"cl-reviews-e2e-tests","number":144,"title":"Cl reviews e2e tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-16/pull/144"},{"author":{"id":"U_kgDOB3CfIg","is_bot":false,"login":"suhritpadakanti","name":""},"headRefName":"sp-intergrationtests","number":138,"title":"Sp intergrationtests","url":"https://github.com/ucsb-cs156-s25/team02-s25-16/pull/138"},{"author":{"id":"U_kgDOCEZbAQ","is_bot":false,"login":"johnhagedorncs","name":"John Hagedorn"},"headRefName":"jh-ucsborg-integration-tests","number":119,"title":"Jh ucsborg integration tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-16/pull/119"},{"author":{"id":"U_kgDOCEZbAQ","is_bot":false,"login":"johnhagedorncs","name":"John Hagedorn"},"headRefName":"jh-ucsborg-index","number":116,"title":"Jh ucsborg index, create, edit","url":"https://github.com/ucsb-cs156-s25/team02-s25-16/pull/116"},{"author":{"id":"U_kgDOCEZbAQ","is_bot":false,"login":"johnhagedorncs","name":"John Hagedorn"},"headRefName":"jh-create-ucsborg-page","number":104,"title":"Jh create ucsborg page","url":"https://github.com/ucsb-cs156-s25/team02-s25-16/pull/104"},{"author":{"id":"U_kgDOCEZbAQ","is_bot":false,"login":"johnhagedorncs","name":"John Hagedorn"},"headRefName":"jh-ucsborg-placeholder-pages","number":103,"title":"jh - ucsborganization placeholder pages + tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-16/pull/103"},{"author":{"id":"U_kgDOCEZbAQ","is_bot":false,"login":"johnhagedorncs","name":"John Hagedorn"},"headRefName":"pc-ucsborganiation-form","number":71,"title":"Pc add form for ucsborganiation","url":"https://github.com/ucsb-cs156-s25/team02-s25-16/pull/71"}]
