
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-16
owner: ucsb-cs156-s25
repo_name: team02-s25-16
pull_requests: [{"author":{"id":"MDQ6VXNlcjYyNDA0OTIx","is_bot":false,"login":"applechristian","name":"Christian Lee"},"headRefName":"cl-MenuItemReview-backend","number":72,"title":"cl - copy backend CRUD operations from team01 for the reviews table","url":"https://github.com/ucsb-cs156-s25/team02-s25-16/pull/72"},{"author":{"id":"U_kgDOCEZbAQ","is_bot":false,"login":"johnhagedorncs","name":"John Hagedorn"},"headRefName":"pc-ucsborganiation-form","number":71,"title":"Pc add form for ucsborganiation","url":"https://github.com/ucsb-cs156-s25/team02-s25-16/pull/71"},{"author":{"id":"MDQ6VXNlcjQ1ODkwOTMy","is_bot":false,"login":"jeffreylin26","name":"Jeffrey Lin"},"headRefName":"jl-helprequest-fixtures","number":70,"title":"added help request fixtures","url":"https://github.com/ucsb-cs156-s25/team02-s25-16/pull/70"}]
