
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-16
owner: ucsb-cs156-s25
repo_name: team02-s25-16
pull_requests: [{"author":{"id":"U_kgDOBojkhQ","is_bot":false,"login":"DerekKirschbaum","name":""},"headRefName":"dk-menuitem-table","number":69,"title":"Dk menuitem table","url":"https://github.com/ucsb-cs156-s25/team02-s25-16/pull/69"},{"author":{"id":"MDQ6VXNlcjc3MzEwNzE5","is_bot":false,"login":"Wilson730","name":"Wilson Lau"},"headRefName":"WL-RecRequest-fixtures","number":68,"title":"WL - create fixtures for RecommendationRequest","url":"https://github.com/ucsb-cs156-s25/team02-s25-16/pull/68"},{"author":{"id":"MDQ6VXNlcjc3MzEwNzE5","is_bot":false,"login":"Wilson730","name":"Wilson Lau"},"headRefName":"WL-RecommendationRequest-backend","number":67,"title":"WL - Created backend for swagger endpoints for RecommendationRequest","url":"https://github.com/ucsb-cs156-s25/team02-s25-16/pull/67"},{"author":{"id":"U_kgDOBojkhQ","is_bot":false,"login":"DerekKirschbaum","name":""},"headRefName":"dk-menuitem-form","number":66,"title":"Dk menuitem form","url":"https://github.com/ucsb-cs156-s25/team02-s25-16/pull/66"},{"author":{"id":"U_kgDOBojkhQ","is_bot":false,"login":"DerekKirschbaum","name":""},"headRefName":"dk-menuitem-fixtures","number":63,"title":"Dk menuitem fixtures","url":"https://github.com/ucsb-cs156-s25/team02-s25-16/pull/63"}]
