
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-16
owner: ucsb-cs156-s25
repo_name: team02-s25-16
pull_requests: [{"author":{"id":"MDQ6VXNlcjc3MzEwNzE5","is_bot":false,"login":"Wilson730","name":"Wilson Lau"},"headRefName":"WL-RecRequest-editpage","number":82,"title":"WL - RecRequest edit page ","url":"https://github.com/ucsb-cs156-s25/team02-s25-16/pull/82"},{"author":{"id":"MDQ6VXNlcjc3MzEwNzE5","is_bot":false,"login":"Wilson730","name":"Wilson Lau"},"headRefName":"WL-RecRequest-indexpage","number":81,"title":"WL - RecRequest index page ","url":"https://github.com/ucsb-cs156-s25/team02-s25-16/pull/81"},{"author":{"id":"MDQ6VXNlcjc3MzEwNzE5","is_bot":false,"login":"Wilson730","name":"Wilson Lau"},"headRefName":"WL-RecRequest-createpage","number":80,"title":"WL - RecRequest create page ","url":"https://github.com/ucsb-cs156-s25/team02-s25-16/pull/80"},{"author":{"id":"MDQ6VXNlcjc3MzEwNzE5","is_bot":false,"login":"Wilson730","name":"Wilson Lau"},"headRefName":"WL-RecRequest-placeholders","number":79,"title":"WL - Copy Placeholders for RecRequest","url":"https://github.com/ucsb-cs156-s25/team02-s25-16/pull/79"},{"author":{"id":"MDQ6VXNlcjc3MzEwNzE5","is_bot":false,"login":"Wilson730","name":"Wilson Lau"},"headRefName":"WL-RecRequest-table","number":78,"title":"WL - Created the table visual for each RecRequest","url":"https://github.com/ucsb-cs156-s25/team02-s25-16/pull/78"},{"author":{"id":"MDQ6VXNlcjc3MzEwNzE5","is_bot":false,"login":"Wilson730","name":"Wilson Lau"},"headRefName":"WL-RecRequest-form","number":77,"title":"WL - added form for RecRequest","url":"https://github.com/ucsb-cs156-s25/team02-s25-16/pull/77"},{"author":{"id":"U_kgDOCEZbAQ","is_bot":false,"login":"johnhagedorncs","name":"John Hagedorn"},"headRefName":"pc-ucsborganiation-form","number":71,"title":"Pc add form for ucsborganiation","url":"https://github.com/ucsb-cs156-s25/team02-s25-16/pull/71"}]
